// web/src/lib/components/Editor.svelte
<script lang="ts">
	import { editorData } from '$lib/store';
	import type monaco from 'monaco-editor';
	import editorWorker from 'monaco-editor/esm/vs/editor/editor.worker?worker';
	import cssWorker from 'monaco-editor/esm/vs/language/css/css.worker?worker';
	import htmlWorker from 'monaco-editor/esm/vs/language/html/html.worker?worker';
	import jsonWorker from 'monaco-editor/esm/vs/language/json/json.worker?worker';
	import tsWorker from 'monaco-editor/esm/vs/language/typescript/ts.worker?worker';
	import { onMount } from 'svelte';

	let container: HTMLDivElement = null;
	let editor: monaco.editor.IStandaloneCodeEditor;
	let Monaco;

	onMount(async () => {
		self.MonacoEnvironment = {
			getWorker: function (_moduleId: string, label: string) {
				if (label === 'json') {
					return new jsonWorker();
				}
				if (label === 'css' || label === 'scss' || label === 'less') {
					return new cssWorker();
				}
				if (label === 'html' || label === 'handlebars' || label === 'razor') {
					return new htmlWorker();
				}
				if (label === 'typescript' || label === 'javascript') {
					return new tsWorker();
				}
				return new editorWorker();
			}
		};

		Monaco = await import('monaco-editor');
		editor = Monaco.editor.create(container, {
			value: $editorData,
			language: 'text'
		});

		return () => {
			editor.dispose();
		};
	});

	export function save(): void {
		editorData.set(editor.getValue());
	}
</script>

<div class="h-full overflow-hidden" bind:this={container} />

// web/src/components/Editor.vue
<template>
  <div ref="container" class="container"></div>
</template>

<style scoped>
.container {
  height: 100%;
  overflow: hidden;
}
</style>

<script lang="ts">
import {
  defineComponent, onMounted, ref, watchEffect,
} from "vue";

import { http, httpPut, HttpResponse } from "../utils";

import * as monaco from "monaco-editor";
import EditorWorker from "monaco-editor/esm/vs/editor/editor.worker.js?worker";
import JsonWorker from "monaco-editor/esm/vs/language/json/json.worker.js?worker";

// @ts-ignore
self.MonacoEnvironment = {
  getWorker: function (moduleId, label) {
    if (label === "json") {
      return new JsonWorker();
    }
    return new EditorWorker();
  },
};

export default defineComponent({
  name: "Editor",
  props: {
    filepath: String,
  },
  emits: [
    'saved',
  ],
  setup(props, { attrs, emit }) {
    const container = ref(null);
    var editor = null;

    watchEffect(async () => {
      if (props.filepath == null) {
        return;
      }
      let response = await http(`/api/files?path=${props.filepath}`, "text");
      editor.setValue(response.parsedBody);
    });

    onMounted(() => {
      editor = monaco.editor.create(container.value, {
        value: "",
        language: "text",
      });
    });

    const save = async () => {
      const response = await httpPut(`/api/files?path=${props.filepath}`, editor.getValue());
    };

    return {
      container,
      save,
    };
  },
});
</script>
