// web/src/lib/components/SInput.svelte
<script lang="ts">
	export let value = '';
	export let placeholder: string;
	export let type: string;

	function handleInput(event: Event & { currentTarget: EventTarget & HTMLInputElement }): void {
		value = event.currentTarget.value;
	}
</script>

<div class="w-full h-12 relative overflow-auto">
	<input
		{type}
		name="input"
		placeholder=" "
		on:input={handleInput}
		on:keypress
		{value}
		class="w-full h-full text-basics-300 pt-6 border-none outline-none"
	/>
	<label
		for="input"
		class="absolute left-0 bottom-0 h-full w-full pointer-events-none border-b border-solid border-black"
	>
		<span class="content absolute bottom-1 left-0 transition-all duration-300 ease-in-out"
			>{placeholder}</span
		>
	</label>
</div>

<style>
	label::after {
		content: '';
		transform: scaleX(0);
		@apply h-full w-full absolute left-0 bottom-[-1px] duration-300 ease-in-out border-b-2 border-solid border-primary;
	}

	input:focus + label .content,
	input:not(:placeholder-shown) + label .content {
		transform: translateY(-100%);
		@apply text-primary text-sm;
	}

	input:focus + label::after,
	input:not(:placeholder-shown) + label::after {
		transform: scaleX(1);
	}
</style>

// web/src/components/SInput.vue
<template>
  <div class="container">
    <input
      :type="type"
      name="input"
      placeholder=" "
      :value="modelValue"
      @input="$emit('update:modelValue', $event.target.value)"
    />
    <label for="input" class="label">
      <span class="content">{{ placeholder }}</span>
    </label>
  </div>
</template>

<style scoped>
.container {
  width: 100%;
  height: 42px;
  position: relative;
  overflow: auto;
}

.container input {
  width: 100%;
  height: 100%;
  color: #595f6e;
  padding-top: 20px;
  border: none;
  box-sizing: border-box;
  outline: none;
}

.container label {
  position: absolute;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  pointer-events: none;
  border-bottom: 1px solid black;
}

.container label::after {
  content: "";
  height: 100%;
  width: 100%;
  position: absolute;
  left: 0;
  bottom: -1px;
  border-bottom: 2px solid rgb(64, 158, 255);
  transform: scaleX(0);
  transition: .3s cubic-bezier(.25,.8,.5,1);
}

.content {
  position: absolute;
  bottom: 5px;
  left: 0;
  transition: .3s cubic-bezier(.25,.8,.5,1);
}

.container input:focus + .label .content, .container input:not(:placeholder-shown) + .label .content {
  transform: translateY(-100%);
  font-size: 14px;
  color: rgb(64, 158, 255);
}

.container input:focus + label::after, .container input:not(:placeholder-shown) + label::after {
  transform: scaleX(1);
}
</style>

<script lang="ts">
import { computed, defineComponent, ref, watchEffect } from "vue";
export default defineComponent({
  name: "SInput",
  props: {
    modelValue: String,
    placeholder: String,
    type: {
      type: String,
      required: true,
    }
  },
  emits: ["update:modelValue"],
});
</script>
