// web/src/lib/components/SScroller.svelte
<script lang="ts">
	import { afterUpdate, beforeUpdate } from 'svelte';

	let container;
	let needsAutoscroll: boolean;

	export let autoscroll = false;

	beforeUpdate(() => {
		needsAutoscroll =
			container && container.offsetHeight + container.scrollTop > container.scrollHeight - 20;
	});

	afterUpdate(() => {
		if (needsAutoscroll && autoscroll) container.scrollTo(0, container.scrollHeight);
	});
</script>

<div class="container" bind:this={container}>
	<slot />
</div>

<style scoped>
	.container {
		height: 100%;
		overflow: auto;
	}
</style>

// web/src/components/SScroller.vue
<template>
  <div class="container" ref="container">
    <slot></slot>
  </div>
</template>

<style scoped>
.container {
  height: 100%;
  overflow: auto;
}
</style>

<script lang="ts">
import {
  defineComponent, onUpdated, ref,
} from "vue";

export default defineComponent({
  name: "SScroller",
  props: {
    autoscroll: {
      type: Boolean,
      default: false,
    }
  },
  setup(props, { attrs }) {
    const container = ref(null);

    onUpdated(() => {
       if (
        container.value.scrollTop < container.value.scrollHeight &&
        props.autoscroll
      ) {
        container.value.scrollTop = container.value.scrollHeight;
      }
    });

    return {
      container,
    };
  },
});
</script>
