// web/src/components/RCON.vue
<template>
  <s-card width="600px" height="400px">
    <s-card-title>RCON</s-card-title>
    <s-card-content>
      <s-scroller :autoscroll="autoscroll">
        <div v-for="(log, index) in logs" :key="index" class="msg">
          {{ log }}
        </div>
      </s-scroller>
    </s-card-content>
    <s-card-actions>
      <div class="actions">
        <div class="settings">
          <s-switch v-model="autoscroll">Autoscroll:</s-switch>
        </div>
        <div>
          <s-input
            type="text"
            placeholder="Command"
            v-model="command"
            v-on:keyup.enter="submit"
          />
          <s-button @click.stop="submit">Send</s-button>
        </div>
      </div>
    </s-card-actions>
  </s-card>
</template>

<style scoped>
.msg {
  margin-top: 3px;
  padding: 5px;
  border-radius: 3px;
  background: #f5f5f5;
}

.actions {
  width: 100%;
}

.actions > div {
  display: flex;
}

.actions > .settings {
  justify-content: flex-end;
  margin: 8px;
}
</style>

<script lang="ts">
import { defineComponent, onMounted, ref } from "vue";
import { Notify } from "./SNotification";

var backendURL = "ws://localhost:8080/api/rcon";

if (import.meta.env.MODE == "production") {
  backendURL = "wss://" + document.location.host + "/api/rcon";
}

export default defineComponent({
  name: "rcon",
  setup({}, { attrs }) {
    const logs = ref([]);
    const command = ref("");
    const autoscroll = ref(true);
    var conn;

    onMounted(() => {
      conn = new WebSocket(backendURL);
      conn.onerror = (event: ErrorEvent) => {
        Notify(
          `Could not establish WebSocket conneciton. Try reloading the page. ${JSON.stringify(
            event,
            ["message", "arguments", "type", "name"]
          )}`
        );
        conn = null;
      };
      conn.onclose = function (evt) {
        if (conn == null) {
          return;
        }
        Notify("Connection closed.");
      };
      conn.onmessage = (event: MessageEvent<string>) => {
        logs.value.push(...event.data.split("\n"));
      };
    });

    const submit = () => {
      if (!conn) {
        return;
      }
      if (command.value === "") {
        Notify("Need to specify command!");
        return;
      }
      conn.send(command.value);
      command.value = "";
    };
    return {
      logs,
      command,
      autoscroll,
      submit,
    };
  },
});
</script>

// web/src/lib/components/RCON.svelte
<script lang="ts">
	import { Notify } from '$lib/store';
	import { onMount } from 'svelte';
	import SButton from './SButton.svelte';
	import SCard from './SCard.svelte';
	import SCardActions from './SCardActions.svelte';
	import SCardContent from './SCardContent.svelte';
	import SCardTitle from './SCardTitle.svelte';
	import SInput from './SInput.svelte';
	import SScroller from './SScroller.svelte';
	import SSwitch from './SSwitch.svelte';

	var backendURL = 'ws://localhost:8080/api/rcon';

	let autoscroll = true;
	let command = '';
	let logs: string[] = [];
	let conn;

	function onKeyPress(event: KeyboardEvent) {
		if (event.key == 'Enter') {
			submit();
		}
	}

	function submit() {
		Notify({
			message: 'Sending command...',
			type: 'info',
			dismissible: false,
			timeout: 3000
		});
		if (!conn) {
			return;
		}
		if (command === '') {
			Notify({
				message: 'Need to specify command!',
				type: 'error',
				dismissible: true,
				timeout: 3000
			});
			return;
		}
		conn.send(command);
		command = '';
	}

	onMount(() => {
		if (import.meta.env.MODE == 'production') {
			backendURL = 'wss://' + document.location.host + '/api/rcon';
		}
		conn = new WebSocket(backendURL);
		conn.onerror = (event: ErrorEvent) => {
			Notify({
				message: `Could not establish WebSocket conneciton. Try reloading the page. ${JSON.stringify(
					event,
					['message', 'arguments', 'type', 'name']
				)}`,
				type: 'error',
				dismissible: true,
				timeout: 3000
			});
			conn = null;
		};
		conn.onclose = function () {
			if (conn == null) {
				return;
			}
			Notify({
				message: 'Connection closed.',
				type: 'error',
				dismissible: true,
				timeout: 3000
			});
		};
		conn.onmessage = (event: MessageEvent<string>) => {
			logs = [...logs, ...event.data.split('\n')];
		};
	});
</script>

<SCard width="600px" height="400px">
	<SCardTitle>RCON</SCardTitle>
	<SCardContent>
		<SScroller {autoscroll}>
			{#each logs as log}
				<div class="msg">{log}</div>
			{/each}
		</SScroller>
	</SCardContent>
	<SCardActions>
		<div class="actions">
			<div class="settings">
				<SSwitch bind:value={autoscroll}>Autoscroll:</SSwitch>
			</div>
			<div>
				<SInput type="text" placeholder="Command" bind:value={command} on:keypress={onKeyPress} />
				<SButton on:click={submit} disabled={command.length == 0}>Send</SButton>
			</div>
		</div>
	</SCardActions>
</SCard>

<style>
	.msg {
		margin-top: 3px;
		padding: 5px;
		border-radius: 3px;
		background: #f5f5f5;
	}

	.actions {
		width: 100%;
	}

	.actions > div {
		display: flex;
	}

	.actions > .settings {
		justify-content: flex-end;
		margin: 8px;
	}

	.disabled {
		background: red;
	}
</style>
