// web/src/components/SCard/SCard.vue
<template>
  <div v-bind:style="{ width: width, height: height }" :class="$style.card">
    <slot></slot>
  </div>
</template>

<style module>
.card {
  box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 12px 0px;
  padding: 20px;
  border-radius: 4px;
  border: 1px solid rgb(235, 238, 245);
  background-color: rgb(255, 255, 255);
  color: rgb(48, 49, 51);
  transition: all 0.3s ease 0s;
  display: flex;
  flex-direction: column;
  min-width: 240px;
}
</style>

<script lang="ts">
import {
  defineComponent,
} from "vue";

export default defineComponent({
  name: "SCard",
  props: {
    width: String,
    height: String,
  },
});
</script>

// web/src/lib/components/SCard.svelte
<script lang="ts">
	import { css } from '$lib/css';
	export let width: string;
	export let height: string;
</script>

<div use:css={{ width, height }} class="card">
	<slot />
</div>

<style>
	.card {
		--width: auto;
		--height: auto;
		width: var(--width);
		height: var(--height);

		@apply shadow m-4 p-6 border border-solid border-basics-100 rounded-md bg-white text-black transition-all flex flex-col;
	}
</style>
